apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig
metadata:
  name: hippo
  region: eu-west-1
vpc:
  cidr: 10.0.0.0/16
nodeGroups:
  - name: basic
    instanceType: m5.xlarge
    desiredCapacity: 2
    allowSSH: true
    privateNetworking: true
